export const items = [
  { id: 21, name: "Jalkapallo", category: 11 },
  { id: 22, name: "Salibandy", category: 11 },
  { id: 23, name: "Taekwondo", category: 12 },
  { id: 24, name: "Breakdance", category: 13 },
  { id: 25, name: "Hip Hop", category: 13 },
  { id: 26, name: "Tekstiilityöt", category: 14 },
  { id: 27, name: "Puutyöt", category: 14 },
  { id: 28, name: "Katutaide", category: 14 },
  { id: 29, name: "Partio", category: 16 },
  { id: 30, name: "Meripartio", category: 16 },
  { id: 31, name: "Aikido", category: 12 },
  { id: 32, name: "Amerikkalainen jalkapallo", category: 11 },
  { id: 33, name: "Cheerleading", category: 13 },
  { id: 34, name: "Juoksu", category: 17 },
  { id: 35, name: "Tennis", category: 11 },
  { id: 36, name: "Koripallo", category: 11 },
  { id: 37, name: "Lentopallo", category: 11 },
  { id: 38, name: "Karate", category: 12 },
  { id: 39, name: "Potkunyrkkeily", category: 12 },
  { id: 40, name: "Muay Thai", category: 12 },
  { id: 41, name: "Brasilialainen jujutsu", category: 12 },
  { id: 42, name: "Itsepuolustus", category: 12 },
  { id: 43, name: "Vapaaottelu", category: 12 },
  { id: 44, name: "Maantiepyöräily", category: 18 },
  { id: 45, name: "Alamäkipyöräily", category: 18 },
  { id: 46, name: "Maastopyöräily", category: 18 },
  { id: 47, name: "Kalliokiipeily", category: 19 },
  { id: 48, name: "Boulderointi", category: 19 },
  { id: 49, name: "Seinäkiipeily", category: 19 },
  { id: 50, name: "Taiji", category: 12 },
  { id: 51, name: "Pesäpallo", category: 11 },
  { id: 52, name: "Tankotanssi", category: 13 },
  { id: 53, name: "Lukkopaini", category: 12 },
  { id: 54, name: "Jääkiekko", category: 11 },
  { id: 55, name: "Purjehdus", category: 20 },
  { id: 56, name: "Laskettelu", category: 21 },
  { id: 57, name: "Lumilautailu", category: 21 },
  { id: 58, name: "Freeski", category: 21 },
  { id: 59, name: "Ratsastus", category: 22 },
  { id: 60, name: "Kouluratsastus", category: 22 },
  { id: 61, name: "Esteratsastus", category: 22 },
  { id: 62, name: "Ratsastusjousiammunta", category: 22 },
  { id: 63, name: "Hevospallo", category: 22 },
  { id: 64, name: "Akrobatiaratsastus", category: 22 },
  { id: 65, name: "Suunnistus", category: 23 },
  { id: 66, name: "Laitesukellus", category: 24 },
  { id: 67, name: "Uppopallo", category: 11 }
];
